import { AppNavbar } from "../components/AppNavbar";
import { TPProviders } from "../context/TPProviders";
import { GlobalEffect } from "./GlobalEffect";
import "./globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <TPProviders>
          <GlobalEffect />
          <div className="dark text-foreground bg-background min-h-screen">
            <div className="max-w-[1024px] mx-auto flex flex-col min-h-screen px-[10px]">
              <AppNavbar />
              <div className="flex flex-1">
                {children}
              </div>
            </div>
          </div>
        </TPProviders>
      </body>
    </html>
  );
}
